stages:
  - build
  - scan
  - deploy

variables:
  DOTNET_ROOT: "C:\\Program Files\\dotnet"
  DEPLOY_BASE_PATH: "D:\\CIM\\ARGO"

build_job:
  stage: build
  tags:
    - CS-CIM
  script:
    - echo "Start Build..."
    - dotnet --version
    - dotnet restore
    - dotnet build CSCIMAPI/CSCimAPI.csproj --configuration Release
    - dotnet publish CSCIMAPI/CSCimAPI.csproj -c Release -o publish
  artifacts:
    paths:
      - publish/
    expire_in: 1 hour

scan_job:
  stage: scan
  tags:
    - CS-CIM
  script:
    - echo "Start DevSkim Scan..."
    - '& "D:\Tools\DevSkim\devskim.exe" analyze -I . -r rules.json -f sarif -O scan_result.sarif -g rules.json, Program.cs'    
    - 'type scan_result.sarif'
    - python sarif_to_html.py scan_result.sarif scan_report.html


  artifacts:
    paths:
      - rules.json
      - scan_result.sarif
      - scan_report.html

    expire_in: 1 hour


deploy_job:
  stage: deploy
  tags:
    - CS-CIM
  only:
    - main
    - develop
  script:
    - echo "執行部署腳本..."
    - powershell ./deploy.ps1
